# 经典示例
```python
try:
  f()
  # ...
except Exception as e:
  # ...code that handles the error...
```

```python
rc = f()
if rc == 0:
  # ...
else:
  # ...code that handles the error...
```

# 更大规模的示例（从10层调用中获取错误）
```python
# TODO
```

# 错误与返回值混在一起
```python
class Number(object):
    def add(Number n) -> Number:
        pass
    def sub(Number n) -> Number:
        pass
    def multi(Number n) -> Number:
        pass
    def div(Number n) -> Number:
        pass

x, y = Number(), Number()
try:
    # ...
    sum = x.add(y)
    diff = x.sub(y)
    prod = x.multi(y)
    quot = x.div(y)
    # ...
except Overflow:
    # some_deal
except Underflow:
    # some_deal
except DivideByZero:
    # some_deal
```

```python
# TODO 用 return code 来实现 
```
